### ISSUE TITLE
Python errors with check-mod-load-unload.sh on CHT device

### ISSUE THREAD

**Issue by plbossart** [thesofproject/sof-test#288]
````
root@Zotac:~/sof-test/test-case# ./check-kmod-load-unload.sh -l 10
2020-07-13 19:30:05 UTC [REMOTE_INFO] Pulseaudio disabled
2020-07-13 19:30:05 UTC [REMOTE_INFO] ===== Starting iteration 1 of 10 =====
2020-07-13 19:30:05 UTC [REMOTE_INFO] wait dsp power status to become suspended
Traceback (most recent call last):
  File "/root/sof-test/tools/sof-dump-status.py", line 405, in <module>
    print(sysinfo.sys_power['run_status'][ret_args['dsp_status']]['status'])
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/sof-test/tools/sof-dump-status.py", line 405, in <module>
    print(sysinfo.sys_power['run_status'][ret_args['dsp_status']]['status'])
IndexError: list index out of range
````

**Comment by aiChaoSONG** [comment]
@plbossart We don't have CHT device with us, Do you know someone have this device and share with us? then we can have a look.

**Comment by plbossart** [comment]
> this

I can't share the device, so it's going to be interesting to debug. My Python skills are rusty, but can't we add some range checks on parameters here?

**Comment by plbossart** [comment]
@bardliao @aiChaoSONG I also get this on a TGL device w/ SoundWire SDCA

````
~/sof-test/test-case# ./check-kmod-load-unload.sh 
2020-09-22 14:26:19 UTC [INFO] ===== Starting iteration 1 of 2 =====
2020-09-22 14:26:19 UTC [INFO] wait dsp power status to become suspended
Traceback (most recent call last):
  File "/root/sof-test/tools/sof-dump-status.py", line 405, in <module>
    print(sysinfo.sys_power['run_status'][ret_args['dsp_status']]['status'])
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/sof-test/tools/sof-dump-status.py", line 405, in <module>
    print(sysinfo.sys_power['run_status'][ret_args['dsp_status']]['status'])
IndexError: list index out of range
Traceback (most recent call last):
  File "/root/sof-test/tools/sof-dump-status.py", line 405, in <module>
    print(sysinfo.sys_power['run_status'][ret_args['dsp_status']]['status'])
IndexError: list index out of range
````

I think it comes from the Power Status that doesn't exist:
````
Power Info:
	Current option:	s2idle
		option:	[s2idle]
	Wakeup Count:	1
Power Status:
````

**Comment by plbossart** [comment]
I can get the scripts to work with the following diff

````
diff --git a/tools/sof-dump-status.py b/tools/sof-dump-status.py
index 0a64bc8..3dc80d6 100755
--- a/tools/sof-dump-status.py
+++ b/tools/sof-dump-status.py
@@ -180,7 +180,7 @@ class clsSYSCardInfo():
         for pci_info in self.pci_lst:
             if 'device_id' in pci_info:
                 self.sys_power['run_status'].append({'map_id': pci_info['device_id'], 'status': 'unsupported'})
-            exit_code, output=subprocess.getstatusoutput("cat /sys/bus/pci/devices/0000:%s/power/runtime_status" % (pci_info['pci_id']))
+            exit_code, output=subprocess.getstatusoutput("cat /sys/bus/pci/devices/%s/power/runtime_status" % (pci_info['pci_id']))
             if exit_code != 0:
                 continue
             self.sys_power['run_status'].append({'map_id': pci_info['pci_id'], 'status': output})
````

@aiChaoSONG I think the parsing of the lspci output doesn't work here, the leading 0000 are not removed when parsing and need to be removed from the string.

**Comment by aiChaoSONG** [comment]
@plbossart I think the output from below code is an empty string, that's why you don't see the python index error and you get `Power Info:  `
`exit_code, output=subprocess.getstatusoutput("cat /sys/bus/pci/devices/%s/power/runtime_status" % (pci_info['pci_id']))`

I may need your help to:
- print the pci_info['pci_id']
-  run the command: `ls /sys/bus/pci/devices/` on your CHT device

**Comment by plbossart** [comment]
@aiChaoSONG The pci issue was on a TGL device and @bardliao should be able to help on the same time zone

**Comment by bardliao** [comment]
@plbossart @aiChaoSONG ./check-kmod-load-unload.sh works fine on my TGL+SDCA platform.
See [check-kmod-load-unload_output.txt](https://github.com/thesofproject/sof-test/files/5273011/check-kmod-load-unload_output.txt)
But if I add print(self.pci_lst) as below
```patch
diff --git a/tools/sof-dump-status.py b/tools/sof-dump-status.py
index 0a64bc8..5539874 100755
--- a/tools/sof-dump-status.py
+++ b/tools/sof-dump-status.py
@@ -184,6 +184,7 @@ class clsSYSCardInfo():
             if exit_code != 0:
                 continue
             self.sys_power['run_status'].append({'map_id': pci_info['pci_id'], 'status': output})
+            print(self.pci_lst)

     def loadDAPM(self, filter = "all"):
         sound_path="/sys/kernel/debug/asoc"

```
It will fail with
```
./check-kmod-load-unload.sh
2020-09-24 02:06:48 UTC [INFO] Pulseaudio disabled
2020-09-24 02:06:48 UTC [INFO] ===== Starting iteration 1 of 2 =====
2020-09-24 02:06:48 UTC [INFO] wait dsp power status to become suspended
2020-09-24 02:07:05 UTC [ERROR] dsp is not suspended after 15s, end test
2020-09-24 02:07:05 UTC [ERROR] Starting func_exit_handler(), exit status=1, FUNCNAME stack:
2020-09-24 02:07:05 UTC [ERROR]  die()  @  ./../case-lib/lib.sh
2020-09-24 02:07:05 UTC [ERROR]  main()  @  ./check-kmod-load-unload.sh:69
nohup: redirecting stderr to stdout
2020-09-24 02:07:05 UTC [INFO] Restoring pulseaudio
2020-09-24 02:07:06 UTC [INFO] Restoring pulseaudio takes 1 seconds
2020-09-24 02:07:06 UTC [INFO] Test Result: FAIL!
```
